// This file is auto-generated by scripts/generate-messages.js
// Do not edit manually - changes will be overwritten

import * as paraglide from './paraglide/messages';

export const general = {
  back_to_home: paraglide["general.back_to_home"]
};
export const privacy = {
  short_description: paraglide["privacy.short_description"],
  umami_explainer: paraglide["privacy.umami_explainer"]
};
export const root = {
  short_description: paraglide["root.short_description"]
};

export const m = {
  general: {
    back_to_home: paraglide["general.back_to_home"]
  },
  privacy: {
    short_description: paraglide["privacy.short_description"],
    umami_explainer: paraglide["privacy.umami_explainer"]
  },
  root: {
    short_description: paraglide["root.short_description"]
  }
};

export default m;
